version: 2
jobs:
  check_code:
    docker:
      - image: circleci/node:erbium-stretch

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit:ci

workflows:
  version: 2
  build:
    jobs:
      - check_code
