version: 2
jobs:
  check_code:
    docker:
      - image: circleci/node:erbium-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd ~/repo && yarn install
      - run: cd ~/repo && yarn run lint
      - run: cd ~/repo && yarn run test:unit:ci

workflows:
  version: 2
  build:
    jobs:
      - check_code
